# Generated by Django 5.2.8 on 2025-11-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
