# Generated by Django 5.2.8 on 2025-11-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entry_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
